version: '3.4'
services:
  postgress:
    container_name: threads-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgress_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgress_data:
